Postgers implementation and databases setup
IshmeetSingh06/ruby-library pull request #3
Opened 2023-07-31 11:39 UTC by IshmeetSingh06

This branch consists of postures implementation and creates the tables if they don't exist

2023-08-01 02:38 UTC, neeraj33negi commented on lib/library_db.rb
> +      puts "An error occurred while connecting to postgres : #{error.message}"
ideally app should exit when DB connection fails,

2023-08-01 02:38 UTC, neeraj33negi commented on lib/user.rb
> +    self.last_name= last_name unless last_name.nil? || last_name.empty?
space before `=`

2023-08-01 02:38 UTC, neeraj33negi commented on lib/user.rb
> +    self.last_name= last_name unless last_name.nil? || last_name.empty?
also we dont need handling this, adding these conditions has no impact on what is assigned to last_name

2023-08-01 05:01 UTC, gagan93jtg requested changes

2023-08-01 05:01 UTC, gagan93jtg commented on lib/library_db.rb
> +class LibraryDB
can we call it `DatabaseConnector`? Our app might expand and just calling this `LibraryDB` might confuse.

2023-08-01 05:01 UTC, gagan93jtg commented on lib/library_db.rb
> +      exit(false)
See how we can use return codes to send some useful information to operating system (like `exit(1)` or something similar)

2023-08-01 05:01 UTC, gagan93jtg commented on lib/library_db.rb
> +    hashed_password = BCrypt::Password.create('admin@123')
can we take this from ENV so that we can configure our own admin password?

2023-08-01 05:01 UTC, gagan93jtg commented on lib/library_db.rb
> +    result = self.conn.exec_params('SELECT EXISTS (SELECT 1 FROM users WHERE username = $1)',['admin@library'])
why nested query? can we write this without nesting?

2023-08-01 05:01 UTC, gagan93jtg commented on main.rb
> +require './lib/library_app.rb'
Let's call this runner.rb or boot.rb. Such names are used for files that startup the application

2023-08-01 05:01 UTC, gagan93jtg commented on lib/library_app.rb
> +class LibraryApp
`application.rb`

2023-08-01 05:01 UTC, gagan93jtg commented on lib/book.rb
> +class Book
Three PORO classes can be moved to a nested folder because they're different from rest of the files :)

2023-08-01 06:22 UTC, gagan93jtg commented on lib/database_connector.rb
> +      ['admin@library', hashed_password, 'admin', true]
1. why hardcoding this when we have taken this out in the ENV variable (as checking the same in lint 79).
2. Let's not put `PG` prefix here. This environment configuration is not related to postgres. It's our admin user, not postgres admin user.

2023-08-01 06:27 UTC, PramanSatya commented
Please change base branch

2023-08-02 04:03 UTC, gagan93jtg approved these changes
LGTM. Please merge after @PramanSatya's approval

2023-08-02 04:04 UTC, gagan93jtg commented
@IshmeetSingh06 there are some conflicts from the base branch. Please resolve

2023-08-02 06:50 UTC, PramanSatya approved these changes

2023-08-02 07:12 UTC, merged